### ISSUE TITLE
ODBC Mismatch

### ISSUE THREAD

**Issue by sqr33** [vanderlowe/myPersonality#1]
Hi Ilmo,

this is not a bug but maybe something that you want to add to the manual:

When I started myPersonality() in R  (on Windows) and entered password and username, i got the following error:  "[Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and Application"   (The German error would be "Der angegebene DSN weist eine nicht übereinstimmende Architektur von Treiber und Anwendung auf").

It seems this is because I was using 32Bit R and and 64 bit ODBC driver from MySQL.

 Those two versions have to match. So the solution is either to run R in 64 bit when the 64 bit version of ODBC is used, or alternatively, if people want to run R in 32bit, configure the data-access by running this C:\Windows\SysWOW64\odbcad32.exe (as the 32 bit configuration can not be accessed through the control panel on a x64 Windows).

After fixing it, I could not proceed further as the username which worked for the wiki did not let me login on the server specified in the manual.

**Comment by vanderlowe** [comment]
This is a good point. I'll update the instructions.
