### ISSUE TITLE
Synchronisation of Table Names

### ISSUE THREAD

**Issue by sqr33** [vanderlowe/myPersonality#3]
Hi Ilmo,

I was trying to use the myPersonalitySQL function and tried to use the same table names as are shown in myPersonality. However, it did not work because internally, the tables have different names than (e.g. fb_friendship inside the database while it is visible as facebook_friendships() ). 

I think it would be helpful for the users if they have the same name. And you could perhaps then even drop a meta table then? Or is there a reason for the distinction?

Cheers,
Alex

**Comment by vanderlowe** [comment]
Hi Alex,

The data access functions were named to be as descriptive as possible (whereas the table names are very brief and not always self-evident, such as 'swl', 'demog', and 'freq'). Although the database table names may make sense to programmers, I wanted to keep in mind that the user base for the package might not have a lot of programming experience and would probably be more productive with transparent, human readable function names.

Ideally, I would have liked to rename the table names directly in the database, but for legacy reasons this is not feasible, as a lot of the scripts that generate the tables would need to be modified to accomplish this. Thus, it was easier to create _meta_tables table that maps the legacy names to descriptive names.

However, getting the name of the actual database table behind the access function is easy: just type the function name without the parentheses.

For example, typing `employers` will return:

``` R
function(...) { mySQL.table.name <- 'fb_employer'
    return(myPersonality:::createVirtualTable(mySQL.table.name, ...))
  }
```

As you can see, `mySQL.table.name <- 'fb_employer'` on the first line gives you the name of the table (`fb_employer`) to use with `myPersonalitySQL`.
